/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import kelas.category;
import kelas.product;


/**
 *
 * @author X1 Carbon
 */
public class Frameproduct extends javax.swing.JFrame {

    /**
     * Creates new form Frameproduct
     */
    public Frameproduct() {
        initComponents();
        loadTable();
        reset ();
        comboBox ();
    }
    
        void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PRODUK");
        model.addColumn("PRODUK");
        model.addColumn("DESKRIPSI");
        model.addColumn("HARGA");
        model.addColumn("KATEGORI");

        try {
            product pro = new product();
            ResultSet data = pro.tampilProduk();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("ID"),
                    data.getString("Nama"),
                    data.getString("Deskripsi"),
                    data.getString("Harga"),
                    data.getString("Kategori"),});

            }

        } catch (SQLException sQLException) {

        }

        dproduct.setModel(model);
    }

    
    void reset() {
        autoID();
        bID.setEditable(true);
        bDeskripsi.setText(null);
        bHarga.setText(null);
        xKategori.setSelectedItem(null);
        bNama.setText(null);
        
    }
    
    
    void comboBox() {
        
        try {
            category cat = new category();
            ResultSet data = cat.tampilcomboBox();
            while (data.next()) {
                String isi = data.getString("category_name");
                xKategori.addItem(isi);
            }
        } catch (SQLException ex) {
        }
    }
    
    void autoID() {

        try {
            product pro = new product();
            ResultSet id = pro.autoID();

            if (id.next()) {
                int auto = id.getInt("ID") + 1;
                bID.setText(String.valueOf(auto));
            } else {
                bID.setText("1");
            }

        } catch (SQLException sQLException) {
        }
    }

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRODUCT = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tTambah = new javax.swing.JButton();
        tUbah = new javax.swing.JButton();
        tHapus = new javax.swing.JButton();
        bID = new javax.swing.JTextField();
        bNama = new javax.swing.JTextField();
        bDeskripsi = new javax.swing.JTextField();
        bHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dproduct = new javax.swing.JTable();
        xKategori = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PRODUCT.setText("PRODUCT");

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        jLabel4.setText("Deskripsi");

        jLabel5.setText("Harga");

        jLabel6.setText("Kategori");

        tTambah.setText("TAMBAH");
        tTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTambahActionPerformed(evt);
            }
        });

        tUbah.setText("UBAH");
        tUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUbahActionPerformed(evt);
            }
        });

        tHapus.setText("HAPUS");
        tHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHapusActionPerformed(evt);
            }
        });

        bNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNamaActionPerformed(evt);
            }
        });

        bHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHargaActionPerformed(evt);
            }
        });

        dproduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dproduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dproductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dproduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTambah)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(14, 14, 14)))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tUbah)
                                .addGap(18, 18, 18)
                                .addComponent(tHapus))
                            .addComponent(bID)
                            .addComponent(bNama)
                            .addComponent(bDeskripsi)
                            .addComponent(bHarga)
                            .addComponent(xKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(PRODUCT, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PRODUCT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(bHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(xKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tTambah)
                            .addComponent(tUbah)
                            .addComponent(tHapus)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHargaActionPerformed

    private void dproductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dproductMouseClicked
        // TODO add your handling code here:
        int baris = dproduct.rowAtPoint(evt.getPoint());
        String ID = dproduct.getValueAt(baris, 0).toString();
        String Nama = dproduct.getValueAt(baris, 1).toString();
        String Desc = dproduct.getValueAt(baris, 2).toString();
        String Harga = dproduct.getValueAt(baris, 3).toString();
        String Kategori = dproduct.getValueAt(baris, 4).toString();
        
        bID.setText(ID);
        bID.setEditable(false);
        bNama.setText(Nama);
        bHarga.setText(Harga);
        bDeskripsi.setText(Desc);
        xKategori.setSelectedItem(Kategori);
    }//GEN-LAST:event_dproductMouseClicked

    private void tTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTambahActionPerformed
        // TODO add your handling code here:
        try {
            product pro = new product();
            category cat = new category();
            pro.setProduct_id(Integer.parseInt(bID.getText()));
            pro.setProduct_name(bNama.getText());
            pro.setProduct_desc(bDeskripsi.getText());
            pro.setProduct_price(Integer.parseInt(bHarga.getText()));
            cat.setCategory_name(xKategori.getSelectedItem().toString());
                        ResultSet data = cat.Konversi();
                        
                        if (data.next()) {
                            String isi = data.getString("category_id");
                            pro.setProduct_cat_id(Integer.parseInt(isi));
                
            }            
            pro.tambahProduk();
        } catch (SQLException sQLException) {
            System.out.println("data tidak masuk");
        }
        
        loadTable();
        reset();
        
    }//GEN-LAST:event_tTambahActionPerformed

    private void tHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHapusActionPerformed
        // TODO add your handling code here:
        try {
            product pro = new product();
            pro.setProduct_id(Integer.parseInt(bID.getText()));
            pro.hapusProduk();
        } catch (SQLException sQLException) {
        }
        
        reset();
        loadTable();
    }//GEN-LAST:event_tHapusActionPerformed

    private void tUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUbahActionPerformed
        // TODO add your handling code here:
        try {
            product pro = new product();
            category cat = new category();
            pro.setProduct_id(Integer.parseInt(bID.getText()));
            pro.setProduct_name(bNama.getText());
            pro.setProduct_desc(bDeskripsi.getText());            
            pro.setProduct_price(Integer.parseInt(bHarga.getText()));
            cat.setCategory_name(xKategori.getSelectedItem().toString());
                        ResultSet data = cat.Konversi();
                        
                        if (data.next()){
                            String isi = data.getString("category_id");
                            pro.setProduct_cat_id(Integer.parseInt(isi));
                        }
                        pro.ubahProduct();
        } catch (SQLException sQLException) {
            System.out.println("data tidak masuk");
        }
        loadTable();
        reset();
    }//GEN-LAST:event_tUbahActionPerformed

    private void bNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frameproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frameproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frameproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frameproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frameproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PRODUCT;
    private javax.swing.JTextField bDeskripsi;
    private javax.swing.JTextField bHarga;
    private javax.swing.JTextField bID;
    private javax.swing.JTextField bNama;
    private javax.swing.JTable dproduct;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tHapus;
    private javax.swing.JButton tTambah;
    private javax.swing.JButton tUbah;
    private javax.swing.JComboBox<String> xKategori;
    // End of variables declaration//GEN-END:variables
}
